### ISSUE TITLE
Navigator puts enterView atop.

### ISSUE THREAD

**Issue by pepyakin** [lukaspili/Mortar-architect#22]
When Navigator play a transition it always add destination view as a child of NavigatorView. So it means that enterView will be always on top.
However, this imposes some restrictions on what kind of animations can be achieved with ViewTransition, so if you want to play animate backward transition from B to A you probably out of luck. 

I see a quick solution here: NavigatorView should place enterView below exitView on transition. 
However, I believe that it is responsibility of ViewTransition to add views whenever and however it needs.

**Comment by grundleborg** [comment]
I think I've run into this problem as well. I'm trying to animate a new view sliding in over the top of the old view on a Forward transition, and sliding back out on a Backward transition. The forward one is working great, but the backward transition doesn't seem to work at all, presumably because the entry view, which this time should be below the exit view, is instead appearing above it and thus hiding the transition effects.

**Comment by pepyakin** [comment]
@grundleborg Hi, consider to put this code before your actual animation:

``` java
if (direction == ViewTransitionDirection.FORWARD) {
  enterView.bringToFront()
} else {
  exitView.bringToFront()
}
```

This will bring your view to front, without removing and adding it again (thus, not triggering your view's onAttachToWindow/onDetachFromWindow callbacks)

**Comment by grundleborg** [comment]
Thanks @pepyakin - that works great.
