### ISSUE TITLE
What is the development status of Mortar-Architect?

### ISSUE THREAD

**Issue by grundleborg** [lukaspili/Mortar-architect#28]
Hi @lukaspili , Just wondering what your plans are for this library? I can see that things have been quite quiet round here in recent months, and was wondering if you are still maintaining this library, or if you have moved on to other projects? It's a great library, and I've found it does a fantastic job of providing the plumbing for single-activity apps, so thank you very much for writing it! But before I make too much use of it in publicly deployed apps, I'm keen to understand what the future looks like for it, as a casual observation suggests development has stalled quite a while ago.

**Comment by justincamp** [comment]
I too am curious. It certainly doesn't look good that this question was asked 3 months ago and there's still no response, but this library seems to be a much better option than flow so I'm keeping the hope alive :)

**Comment by lukaspili** [comment]
Hello guys,
I'm sorry for the late reply. I'm busy with several projects so I did not take any time to maintain the github.

I'm using Mortar Architect in all my current projects. I have several apps in production with no problem regarding to the library. Feedback from developers I know that are using the library is also good.

However, the current readme is not up-to-date with the latest version.
I will definitely try to update the documentation and reply to the issues before the end of the month (giving some buffer to myself here, in order to respect the deadline :)

**Comment by Lakedaemon** [comment]
I was wondering about that too. As I'm regularly encountering some crash with flow and dead mortar scopes when onBack is pressed, I'm considering moving to another library like Mortar-Architect

**Comment by lukaspili** [comment]
Unfortunately I won't have time to maintain and evolve Mortar Architect.

The last snapshot version ```1.0-dev3.8-SNAPSHOT``` is stable, bug free (so far, and to my knowledge) and used in production several active apps with consistent user traffic. However the documentation is not up to date at all with the last version, so you have to check the demo project directly (branch ```1.0_dev3.x```).

While I still recommend to stay as far as possible from fragments, I find the following combo to work surprising well: activities acting as containers, and simple custom views associated to a business logic (presenter or view-model or controller or whatever).

Otherwise, Conductor is a solid alternative to flow/mortar/mortar-architect.

Thanks for the interest and contributions to Mortar Architect.
